### ISSUE TITLE
Crash in DisjInterpolator

### ISSUE THREAD

**Issue by wuestholz** [uuverifiers/eldarica#11]
I get a crash with the following stack trace:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsupportedOperationException: empty.head
	at jayhorn.checker.Checker.checkProgram(Checker.java:818)
	at jayhorn.Main.main(Main.java:71)
Caused by: java.lang.UnsupportedOperationException: empty.head
	at scala.collection.immutable.Vector.head(Vector.scala:193)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:438)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:277)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:277)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$16.apply(DisjInterpolator.scala:459)
	at scala.collection.immutable.List.map(List.scala:273)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:459)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1$$anonfun$15.apply(DisjInterpolator.scala:449)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.lazabs$horn$bottomup$DisjInterpolator$$anonfun$$refine$1(DisjInterpolator.scala:449)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.apply(DisjInterpolator.scala:499)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp$1.apply(DisjInterpolator.scala:194)
	at ap.SimpleAPI$.withProver(SimpleAPI.scala:128)
	at lazabs.horn.bottomup.DisjInterpolator$.lazabs$horn$bottomup$DisjInterpolator$$predicateGeneratorHelp(DisjInterpolator.scala:194)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$predicateGenerator$1.apply$mcV$sp(DisjInterpolator.scala:138)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$predicateGenerator$1.apply(DisjInterpolator.scala:138)
	at lazabs.horn.bottomup.DisjInterpolator$$anonfun$predicateGenerator$1.apply(DisjInterpolator.scala:138)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at ap.util.Timeout$.withChecker(Timeout.scala:44)
	at ap.util.Timeout$$anonfun$withTimeoutMillis$1.apply(Timeout.scala:58)
	at ap.util.Timeout$.catchTimeout(Timeout.scala:88)
	at ap.util.Timeout$.withTimeoutMillis(Timeout.scala:61)
	at lazabs.horn.bottomup.DisjInterpolator$.predicateGenerator(DisjInterpolator.scala:155)
	at lazabs.horn.bottomup.DagInterpolator$.interpolatingPredicateGenCEXAndOr(DagInterpolator.scala:156)
	at lazabs.horn.bottomup.SimpleWrapper$$anonfun$solve$1$$anonfun$apply$1$$anonfun$2.apply(SimpleWrapper.scala:69)
	at lazabs.horn.bottomup.SimpleWrapper$$anonfun$solve$1$$anonfun$apply$1$$anonfun$2.apply(SimpleWrapper.scala:69)
	at lazabs.horn.bottomup.HornPredAbs.liftedTree1$1(HornPredAbs.scala:937)
	at lazabs.horn.bottomup.HornPredAbs.<init>(HornPredAbs.scala:917)
	at lazabs.horn.bottomup.SimpleWrapper$$anonfun$solve$1$$anonfun$apply$1.apply(SimpleWrapper.scala:73)
	at lazabs.horn.bottomup.SimpleWrapper$$anonfun$solve$1$$anonfun$apply$1.apply(SimpleWrapper.scala:51)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:53)
	at lazabs.horn.bottomup.SimpleWrapper$$anonfun$solve$1.apply(SimpleWrapper.scala:51)
	at lazabs.horn.bottomup.SimpleWrapper$$anonfun$solve$1.apply(SimpleWrapper.scala:51)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:92)
	at lazabs.horn.bottomup.SimpleWrapper$.solve(SimpleWrapper.scala:51)
	at lazabs.horn.bottomup.SimpleWrapper.solve(SimpleWrapper.scala)
	at jayhorn.solver.princess.PrincessProver.checkSat(PrincessProver.java:334)
	at jayhorn.checker.Checker.checkProgram(Checker.java:811)
	... 1 more
```

Please let me know if I should send a repro.

**Comment by pruemmer** [comment]
Thanks for the report; yes, please explain when/how this exception occurred (which JayHorn input?) and how to reproduce it.

**Comment by wuestholz** [comment]
@pruemmer Thank you very much for looking into this. I have attached the [horn output](https://github.com/uuverifiers/eldarica/files/405086/test.horn.txt). Please let me know if you run into any issues reproducing it.

**Comment by pruemmer** [comment]
Thanks, I could reproduce the crash after massaging the file a bit. Working on a fix ...
[test.horn.txt](https://github.com/uuverifiers/eldarica/files/415669/test.horn.txt)

**Comment by wuestholz** [comment]
@pruemmer Great! Thank you!

**Comment by pruemmer** [comment]
Should be fixed now! (I will also update JayHorn ...)
