### ISSUE TITLE
Using the C front-end in combination with -abstract sometimes leads to exceptions

### ISSUE THREAD

**Issue by pruemmer** [uuverifiers/eldarica#6]
For instance,

philipp@hal4:~/tmp/eldarica/eldarica$ ./eld -assert -abstract regression-tests/horn-hcc/test4.hcc 
Warning: entry function "main" not found
ap.SimpleAPI$SimpleAPIException: java.lang.AssertionError: assertion failed
	at ap.SimpleAPI.ap$SimpleAPI$$evalProverResult(SimpleAPI.scala:1851)
	at ap.SimpleAPI.getStatusHelp(SimpleAPI.scala:1809)
	at ap.SimpleAPI.getStatus(SimpleAPI.scala:1804)
	at lazabs.horn.abstractions.StrideDomain.lazabs$horn$abstractions$StrideDomain$$checkWithTO(LoopDetector.scala:304)
	at lazabs.horn.abstractions.StrideDomain$$anonfun$29$$anonfun$apply$28$$anonfun$apply$34$$anonfun$apply$2.apply$mcV$sp(LoopDetector.scala:357)
	at lazabs.horn.abstractions.StrideDomain$$anonfun$29$$anonfun$apply$28$$anonfun$apply$34$$anonfun$apply$2.apply(LoopDetector.scala:355)
	at lazabs.horn.abstractions.StrideDomain$$anonfun$29$$anonfun$apply$28$$anonfun$apply$34$$anonfun$apply$2.apply(LoopDetector.scala:355)
	at ap.SimpleAPI.scope(SimpleAPI.scala:3005)
	at lazabs.horn.abstractions.StrideDomain$$anonfun$29$$anonfun$apply$28$$anonfun$apply$34.apply(LoopDetector.scala:355)
	at lazabs.horn.abstractions.StrideDomain$$anonfun$29$$anonfun$apply$28$$anonfun$apply$34.apply(LoopDetector.scala:348)
[...]

**Comment by pruemmer** [comment]
fixed
